### ISSUE TITLE
Dime crashes after calendar import

### ISSUE THREAD

**Issue by superkai** [HIIT/dime-server#44]
First I updated Dime and Desktop tracker.
Then I ran it few of my calendars.
It worked sort of ok (at least some calendar entries were recorded)
Then my computer started heating heavy and Java took much CPU and memory.
Then I quit Dime and tried restarting, but got then white label error.

<img width="793" alt="screen shot 2016-02-11 at 17 07 52" src="https://cloud.githubusercontent.com/assets/410528/12980871/fa1e61aa-d0e6-11e5-9198-32650b9986fe.png">
<img width="1904" alt="screen shot 2016-02-11 at 17 38 20" src="https://cloud.githubusercontent.com/assets/410528/12980872/fa21a720-d0e6-11e5-92d3-0f083666eef4.png">

**Comment by superkai** [comment]
Hence, I have 8 core and Java took 741% ...

**Comment by mvsjober** [comment]
It would be useful to see the output from DiMe itself (in the terminal). Either before it started eating CPU or when it crashes afterwards.

Another thing that would be useful is having a copy of your database, but of course this would also contain all of your collected data so I understand if you don't want to share that. If you are OK with sharing it, we should discuss how to copy it. (Don't copy it here in github.)

**Comment by superkai** [comment]
Dime terminal splits something like this at the moment when I try to access it.

2016-02-12 08:08:42.073  INFO 68283 --- [nio-8080-exec-9] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:08:47.073  INFO 68283 --- [nio-8080-exec-1] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:08:52.071  INFO 68283 --- [nio-8080-exec-4] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:08:57.073  INFO 68283 --- [nio-8080-exec-6] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:02.072  INFO 68283 --- [nio-8080-exec-5] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:07.073  INFO 68283 --- [nio-8080-exec-7] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:12.072  INFO 68283 --- [nio-8080-exec-2] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:17.071  INFO 68283 --- [nio-8080-exec-3] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:22.071  INFO 68283 --- [nio-8080-exec-8] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:27.071  INFO 68283 --- [io-8080-exec-10] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:32.071  INFO 68283 --- [nio-8080-exec-9] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:37.070  INFO 68283 --- [nio-8080-exec-1] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:39.093  WARN 68283 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 42122, SQLState: 42S22
2016-02-12 08:09:39.093 ERROR 68283 --- [nio-8080-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column "EVENT0_.IS_SUMMARY" not found; SQL statement:
select event0_.id as id2_0_, event0_.app_id as app_id3_0_, event0_.time_created as time_cre4_0_, event0_.time_modified as time_mod5_0_, event0_.type as type6_0_, event0_.user_id as user_id30_0_, event0_.actor as actor7_0_, event0_.duration as duration8_0_, event0_.end as end9_0_, event0_.altitude as altitud10_0_, event0_.bearing as bearing11_0_, event0_.description_line as descrip12_0_, event0_.horiz_accuracy as horiz_a13_0_, event0_.latitude as latitud14_0_, event0_.longitude as longitu15_0_, event0_.speed as speed16_0_, event0_.vert_accuracy as vert_ac17_0_, event0_.origin as origin18_0_, event0_.start as start19_0_, event0_.resource_id as resourc31_0_, event0_.value as value20_0_, event0_.is_summary as is_summ21_0_, event0_.plain_text_content as plain_t22_0_, event0_.proportion_critical as proport23_0_, event0_.proportion_interesting as proport24_0_, event0_.proportion_read as proport25_0_, event0_.session_id as session26_0_, event0_.funf_value as funf_va27_0_, event0_.probe_name as probe_n28_0_, event0_.query as query29_0_, event0_.dtype as dtype1_0_ from event event0_ left outer join user user1_ on event0_.user_id=user1_.id where user1_.id=? and event0_.time_modified>? order by event0_.start desc [42122-190]
2016-02-12 08:09:39.103 ERROR 68283 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select event0_.id as id2_0_, event0_.app_id as app_id3_0_, event0_.time_created as time_cre4_0_, event0_.time_modified as time_mod5_0_, event0_.type as type6_0_, event0_.user_id as user_id30_0_, event0_.actor as actor7_0_, event0_.duration as duration8_0_, event0_.end as end9_0_, event0_.altitude as altitud10_0_, event0_.bearing as bearing11_0_, event0_.description_line as descrip12_0_, event0_.horiz_accuracy as horiz_a13_0_, event0_.latitude as latitud14_0_, event0_.longitude as longitu15_0_, event0_.speed as speed16_0_, event0_.vert_accuracy as vert_ac17_0_, event0_.origin as origin18_0_, event0_.start as start19_0_, event0_.resource_id as resourc31_0_, event0_.value as value20_0_, event0_.is_summary as is_summ21_0_, event0_.plain_text_content as plain_t22_0_, event0_.proportion_critical as proport23_0_, event0_.proportion_interesting as proport24_0_, event0_.proportion_read as proport25_0_, event0_.session_id as session26_0_, event0_.funf_value as funf_va27_0_, event0_.probe_name as probe_n28_0_, event0_.query as query29_0_, event0_.dtype as dtype1_0_ from event event0_ left outer join user user1_ on event0_.user_id=user1_.id where user1_.id=? and event0_.time_modified>? order by event0_.start desc]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement] with root cause

org.h2.jdbc.JdbcSQLException: Column "EVENT0_.IS_SUMMARY" not found; SQL statement:
select event0_.id as id2_0_, event0_.app_id as app_id3_0_, event0_.time_created as time_cre4_0_, event0_.time_modified as time_mod5_0_, event0_.type as type6_0_, event0_.user_id as user_id30_0_, event0_.actor as actor7_0_, event0_.duration as duration8_0_, event0_.end as end9_0_, event0_.altitude as altitud10_0_, event0_.bearing as bearing11_0_, event0_.description_line as descrip12_0_, event0_.horiz_accuracy as horiz_a13_0_, event0_.latitude as latitud14_0_, event0_.longitude as longitu15_0_, event0_.speed as speed16_0_, event0_.vert_accuracy as vert_ac17_0_, event0_.origin as origin18_0_, event0_.start as start19_0_, event0_.resource_id as resourc31_0_, event0_.value as value20_0_, event0_.is_summary as is_summ21_0_, event0_.plain_text_content as plain_t22_0_, event0_.proportion_critical as proport23_0_, event0_.proportion_interesting as proport24_0_, event0_.proportion_read as proport25_0_, event0_.session_id as session26_0_, event0_.funf_value as funf_va27_0_, event0_.probe_name as probe_n28_0_, event0_.query as query29_0_, event0_.dtype as dtype1_0_ from event event0_ left outer join user user1_ on event0_.user_id=user1_.id where user1_.id=? and event0_.time_modified>? order by event0_.start desc [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:835)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy61.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1885)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1862)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
	at org.hibernate.loader.Loader.doQuery(Loader.java:910)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
	at org.hibernate.loader.Loader.doList(Loader.java:2554)
	at org.hibernate.loader.Loader.doList(Loader.java:2540)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
	at org.hibernate.loader.Loader.list(Loader.java:2365)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:497)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:236)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1300)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:449)
	at org.hibernate.jpa.criteria.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:67)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:110)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:74)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:99)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:90)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:415)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:393)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$DefaultMethodInvokingMethodInterceptor.invoke(RepositoryFactorySupport.java:506)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy96.findByUserAndTimeModifiedIsAfterOrderByStartDesc(Unknown Source)
	at fi.hiit.dime.database.EventDAO.eventsSince(EventDAO.java:122)
	at fi.hiit.dime.database.EventDAO$$FastClassBySpringCGLIB$$8dee5691.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at fi.hiit.dime.database.EventDAO$$EnhancerBySpringCGLIB$$d8fba7ce.eventsSince(<generated>)
	at fi.hiit.dime.WebController.root(WebController.java:125)
	at fi.hiit.dime.WebController$$FastClassBySpringCGLIB$$4986b5b6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at fi.hiit.dime.WebController$$EnhancerBySpringCGLIB$$81d838ba.root(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:57)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

2016-02-12 08:09:42.071  INFO 68283 --- [nio-8080-exec-6] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:47.070  INFO 68283 --- [nio-8080-exec-5] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:52.071  INFO 68283 --- [nio-8080-exec-7] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:09:57.475  INFO 68283 --- [nio-8080-exec-2] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:10:02.070  INFO 68283 --- [nio-8080-exec-3] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1
2016-02-12 08:10:07.070  INFO 68283 --- [nio-8080-exec-8] fi.hiit.dime.ApiController               : Received ping from 0:0:0:0:0:0:0:1

**Comment by mvsjober** [comment]
Thanks! This part is interesting:

     o.h.engine.jdbc.spi.SqlExceptionHelper : Column "EVENT0_.IS_SUMMARY" not found

The field `IS_SUMMARY`has been removed from DiMe, but was used in older versions (before Dec 17, 2015, commit 7832dfbc956527ab704253bd1394094b4d3a24b6). Is it still possible that you are running an older version of DiMe somehow, or is this a false lead? Also, this theory doesn't explain the CPU issue (which probably means DiMe gets stuck in some kind of loop).

This command will tell what is the most recent version in your git repository:

    git log -n 1

This is issue is really hard to debug remotely...

**Comment by superkai** [comment]
Thank you and sorry. The Dime I started was accidentally an old one I used. Now the new one is working ok. Still trying to repeat the overheating thing. Hence, no error anymore.

**Comment by mvsjober** [comment]
No problem, I suppose DiMe should check that the database schema version is incorrect and give a better error message :-)

Let's keep this issue open anyway, to track down the other issue. If you see the high-CPU problem again, please see if there is some suspicious output in the DiMe terminal.
